### ISSUE TITLE
Handle colon in elementid

### ISSUE THREAD

**Issue by kayrus** [andybalholm/cascadia#13]
Similar to that problem:
http://stackoverflow.com/questions/5552462/handling-colon-in-element-id-with-jquery

Double backslashes doesn't work

```
<div id="test:abc" value="123">
```

```
value, exists := doc.Find("div#test:abc").Attr("value")
  if exists == false {
          log.Fatal("Not found\n")
  } else {
  log.Printf("Value: %s\n", value)
```

```
panic: unknown pseudoclass :abc

goroutine 1 [running]:
github.com/andybalholm/cascadia.MustCompile(0x7f1020, 0x23, 0xc82006a380)
        /go/src/github.com/andybalholm/cascadia/selector.go:59 +0x72
github.com/PuerkitoBio/goquery.(*Selection).Find(0xc8201887b0, 0x7f1020, 0x23, 0x0)
        /go/src/github.com/PuerkitoBio/goquery/traversal.go:27 +0x38
main.ExampleScrape()
        /go/src/test/test.go:16 +0x7e
main.main()
        /go/src/test/test.go:42 +0x14
```

**Comment by kayrus** [comment]
This worked for me. This should be mentioned somewhere id documentation.
```
view_state, exists := doc.Find("[id=test\\:abc]").Attr("value")
```

**Comment by andybalholm** [comment]
I don't really see the need to mention it in the documentation, since it is a quirk of CSS selector syntax, not something that's specific to cascadia.

**Comment by kayrus** [comment]
For those who didn't work with CSS before documentation with supported selectors would be helpful.

**Comment by andybalholm** [comment]
You're welcome to write the documentation you think we need and submit a pull request.
