### ISSUE TITLE
Missing :selected and :root

### ISSUE THREAD

**Issue by anacrolix** [andybalholm/cascadia#17]
I believe these selectors are missing.

**Comment by andybalholm** [comment]
I can't see that :selected makes sense in this context (server-side), though we could implement it as a selector that never matches.

**Comment by andybalholm** [comment]
The usage of :root you described at https://github.com/PuerkitoBio/goquery/issues/117 does not seem to match the meaning as documented at https://developer.mozilla.org/en-US/docs/Web/CSS/:root

**Comment by anacrolix** [comment]
I think you are correct. Both `> li:nth-child(2)` and `:selected > li:nth-child(2)` should achieve what I was after in that issue. `:root` should return the query back to the top-level of the entire document.
