### ISSUE TITLE
Performance issues with nth-child pseudo-selector for large documents

### ISSUE THREAD

**Issue by PuerkitoBio** [andybalholm/cascadia#19]
Hello,

With large HTML documents (e.g. thousands of rows in a table), the performance of pseudo-selectors such as `nth-child` really suffers. I created a reproducible test case in https://github.com/PuerkitoBio/cascadia-nth-child after a user reported the issue on the goquery repo, and the results are:

```
2016/08/30 18:42:24 #tbl tr:nth-child(1) td: 30 elements in 1m0.838429805s via goquery
2016/08/30 18:43:25 #tbl tr:nth-child(1) td: 30 elements in 1m0.199170639s via cascadia
2016/08/30 18:43:25 tr + First + td: 30 elements in 10.90311ms
```

That is, selecting with `#tbl tr:nth-child(1) td` takes over a minute while doing the equivalent `doc.Find("#tbl tr").First().Find("td")` takes a few ms.

I think that's mostly by design, having checked the code I believe the (internal) cascadia selectors are stateless so when an `nth-child` is compiled, it loops over all of the node's parent's children, even though `nth-child(1)` may already be found. I don't know of any easy solution, but I wanted to raise the issue and get your thoughts on this.

EDIT: related goquery issue: https://github.com/PuerkitoBio/goquery/issues/126

Thanks,
Martin

**Comment by andybalholm** [comment]
nth-child currently always calculates the index before returning a result. It would probably be possible to short-circuit the calculation and return false once the index is larger than the number passed to nth-child.

**Comment by andybalholm** [comment]
Output of your test after the fix:

    2016/08/31 07:00:24 #tbl tr:nth-child(1) td: 30 elements in 29.548438ms via goquery
    2016/08/31 07:00:24 #tbl tr:nth-child(1) td: 30 elements in 36.058154ms via cascadia
    2016/08/31 07:00:24 tr + First + td: 30 elements in 14.270865ms

**Comment by PuerkitoBio** [comment]
Awesome, thanks!
