### ISSUE TITLE
Support attribute not equal selector

### ISSUE THREAD

**Issue by martinlindhe** [andybalholm/cascadia#20]
`[name!=”value”]`

https://api.jquery.com/attribute-not-equal-selector/

**Comment by andybalholm** [comment]
jQuery-only syntax with an easy workaround is not a high priority for me, but you're welcome to submit a pull request.

**Comment by martinlindhe** [comment]
I'm not aware what the easy workaround is? :-)
Also, if ok i think i'll look into making a pr for this

**Comment by andybalholm** [comment]
Yes, I meant using :not([name="value"])
