### ISSUE TITLE
Error that doesn't allow to parse RSS.

### ISSUE THREAD

**Issue by Mansiper** [andybalholm/cascadia#22]
This selector passes test:
```
	{
		`<item><link>Any link</link><title>Any title</title></item>`,
		"item link:empty",
		[]string{
			"<link>",
		},
	},
```
All other tags work fine. Only link always returns empty text.
For example, ```"item title:empty"``` returns 0 elements.

**Comment by andybalholm** [comment]
The `link` element is a void element in HTML. It can't have any content.

RSS is not HTML, it is XML. Parse it with an XML parser, not an HTML parser.

Trying to parse it as HTML gives you the equivalent of

    <item><link/>Any Link<title>AnyTitle</title></item>
