### ISSUE TITLE
nodeString vs html.Render in test

### ISSUE THREAD

**Issue by suntong** [andybalholm/cascadia#23]
Hi Andy, 

I'm wondering what your considerations were when choosing to use `nodeString()` function (instead of `html.Render()`) in your `selector_test.go` file. I mean, `html.Render()` would work as well, right? 

The reason I'm asking is that, I think people would be more interested in the actual effect on `html.Render()`. Thx.

**Comment by andybalholm** [comment]
Looking back in the git history, I see that html.Render was introduced two weeks before I added the nodeString function to Cascadia. Maybe I didn't think it was mature enough at that point. Or maybe I wanted to keep the strings short by not including child elements. I don't remember any more. That was five years ago.

**Comment by suntong** [comment]
Would you mind if I change it to use `html.Render` and submit a pull request then?

**Comment by andybalholm** [comment]
Go ahead.

**Comment by suntong** [comment]
Alright, will do tonight.
