### ISSUE TITLE
Error HTML.NODE

### ISSUE THREAD

**Issue by YouSelf239** [andybalholm/cascadia#35]
![screenshot 211](https://user-images.githubusercontent.com/37881515/39217129-fe68997c-4837-11e8-8053-34ad005eae57.png)
can u tell me why am i getting this error?

**Comment by andybalholm** [comment]
Probably you haven't installed all the other packages that Cascadia uses. Try running `go get golang.org/x/net/html` first. Or better yet, just install Cascadia with `go get github.com/andybalholm/cascadia`.

**Comment by YouSelf239** [comment]
i did both of those but it didnt work

**Comment by andybalholm** [comment]
What happened when you did them?

**Comment by YouSelf239** [comment]
![screenshot 216](https://user-images.githubusercontent.com/37881515/39217505-c61c9878-4839-11e8-8e7c-8e57bfcf131d.png)
this is what happend

**Comment by andybalholm** [comment]
Try `go get -u golang.org/x/net/html` to make sure you're getting the latest version.

**Comment by YouSelf239** [comment]
when i entered go get -u golang.org/x/net/html it said remote origin not found

**Comment by andybalholm** [comment]
How does it work if you do it from the regular command prompt or PowerShell instead of from MingW?

**Comment by YouSelf239** [comment]
nope, still shows the same error

**Comment by andybalholm** [comment]
How did you install Go? What is the output of `go version`?

**Comment by YouSelf239** [comment]
its go version go1.10.1 windows/amd64

**Comment by andybalholm** [comment]
Is there anything unusual about your network connection?

**Comment by YouSelf239** [comment]
i dont think so, i am trying to use cirnobit repository and this is what is happening

**Comment by andybalholm** [comment]
What is cirnobit repository and how do you "try to use" it?

**Comment by YouSelf239** [comment]
i mean this is how the instructions are
![screenshot 213](https://user-images.githubusercontent.com/37881515/39218112-6355e048-483c-11e8-899a-ca97468ffde7.png)

**Comment by YouSelf239** [comment]
i was following the instructions and this happend

**Comment by andybalholm** [comment]
So it's a program that uses Cascadia?

**Comment by YouSelf239** [comment]
i think yes, it was there

**Comment by andybalholm** [comment]
Did you try `go get -u golang.org/x/net/html` at the regular command prompt?

**Comment by YouSelf239** [comment]
yes, it didnt work either

**Comment by andybalholm** [comment]
Delete the go/src/golang.org directory and try again.

**Comment by YouSelf239** [comment]
nope

**Comment by YouSelf239** [comment]
didnt work

**Comment by andybalholm** [comment]
I don't really have any idea what to try next. But we've figured out that the problem is with installing the golang.org/x/net/html package.

**Comment by YouSelf239** [comment]
Alright, i will try to find a way tomorrow
