### ISSUE TITLE
oss-fuzz integration

### ISSUE THREAD

**Issue by AdamKorcz** [andybalholm/cascadia#45]
Is there interest in integrating the fuzzer in Googles continuous fuzzing service, oss-fuzz?

Through that project, Google will run the fuzzer and send bug reports if a bug is found. Google expects the bugs to be fixed, so the fuzzers can go on and find other bugs, and other than that the service is free of charge.

I will be happy to set it up. All I need is a contact email address that is the official and public contact email of the project.

**Comment by andybalholm** [comment]
Sure, you could do that.

I hadn't thought of having an email address specific to the Cascadia project before, but that's probably a good idea. So here it is: cascadia@balholm.com.
