### ISSUE TITLE
Add support for pseudo-classes

### ISSUE THREAD

**Issue by dolmen** [andybalholm/cascadia#50]
This [commit](https://github.com/benoitkugler/cascadia/commit/fe781f3903331c8921e99e66d95eb3bb81a6c3f7) by @benoitkugler seems to implement pseudo-classes...

**Comment by andybalholm** [comment]
@benoitkugler I notice that you haven't sent a pull request, or merged this to the master branch of your own repository. What is the status of this branch?

**Comment by benoitkugler** [comment]
I indeed haven't polished this branch yet, since I've realized I actually don't need these pseudo-classes. 
I think the branch is mostly functional, but it has not been well tested. 

If there is interest, I should be able do add some tests and submit a PR.

**Comment by andybalholm** [comment]
Obviously @dolmen is interested. I expect more people will be too.

**Comment by benoitkugler** [comment]
I have merged the branch supporting more [pseudo-classes](https://github.com/benoitkugler/cascadia). Some tests are also added.

**Comment by andybalholm** [comment]
Thanks for polishing up your code, @benoitkugler !
