### ISSUE TITLE
Null pointer dereference

### ISSUE THREAD

**Issue by pkitszel** [andybalholm/cascadia#56]
Hi,

my project is using this one as a lib. After some slight changes on webpage that it parsers there is a panic:
https://github.com/Komosa/cf/issues/4

I suppose there is just a need to handle it around lines from stacktrace. But filling an issue for reference.
offending line: gopath.../github.com/andybalholm/cascadia/selector.go:217

**Comment by andybalholm** [comment]
Are you passing in a nil Node?

**Comment by midir99** [comment]
Hey @pkitszel !

I was running into a similar problem few days ago:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x649b8d]

goroutine 63 [running]:
github.com/andybalholm/cascadia.queryInto(0x6bd756?, {0x7f7a1ec38f30, 0xc00129efb0}, {0x0?, 0x64f920?, 0x735300?})
        /home/yoryo/go/pkg/mod/github.com/andybalholm/cascadia@v1.3.1/selector.go:139 +0x2d
github.com/andybalholm/cascadia.QueryAll(...)
        /home/yoryo/go/pkg/mod/github.com/andybalholm/cascadia@v1.3.1/selector.go:152
github.com/midir99/radar/ws.QueryAll(0xc00001efc0?, {0x6bd756?, 0xc000048d38?})
        /home/yoryo/projects/desaparecidos/radar/ws/ws.go:39 +0x71
github.com/midir99/radar/ws.ScrapeGroAlbaAlerts(0x0?, 0x0?)
        /home/yoryo/projects/desaparecidos/radar/ws/gro.go:61 +0x96
created by main.main
        /home/yoryo/projects/desaparecidos/radar/main.go:14 +0x73
exit status 2
```

But it was all my fault as I was passing a `nil` pointer to [`QueryAll`](https://pkg.go.dev/github.com/andybalholm/cascadia#QueryAll) in the `n *html.Node` parameter, all I had to do was adding a validation, so maybe that is what is causing your problem.

**Comment by pkitszel** [comment]
I've just waited a few days, webpage was likely fixed.

pt., 22 lip 2022, 02:08 użytkownik midir99 ***@***.***>
napisał:
