### ISSUE TITLE
call Parse on a group query "a, b" returns error

### ISSUE THREAD

**Issue by krichprollsch** [andybalholm/cascadia#62]
Hello,
First thank you very much for cascadia which is a great lib :clap: 

I have an issue calling `cascadia.Parse` with a group query: `a, b`
The error is: `parsing "a, b": 3 bytes left over`.

A wrote a quick test case locally to reproduce the error:
```diff
diff --git a/parser_test.go b/parser_test.go
index 0dacb79..cb29f56 100644
--- a/parser_test.go
+++ b/parser_test.go
@@ -1,6 +1,7 @@
 package cascadia
 
 import (
+	"fmt"
 	"testing"
 )
 
@@ -86,3 +87,15 @@ func TestParseString(t *testing.T) {
 		}
 	}
 }
+
+func TestParseGroup(t *testing.T) {
+	source := "a, b"
+
+	got, err := Parse(source)
+
+	if err != nil {
+		t.Fatalf("parsing %q: got error (%s)", source, err)
+	}
+
+	fmt.Println(got)
+}
```

And here is my output:
```
$ go  test -v --run TestParseGroup
=== RUN   TestParseGroup
    parser_test.go:97: parsing "a, b": got error (parsing "a, b": 3 bytes left over)
--- FAIL: TestParseGroup (0.00s)
FAIL
exit status 1
FAIL    github.com/andybalholm/cascadia 0.002s
```

I think something is wrong into into https://github.com/andybalholm/cascadia/blob/master/parser.go#L854 when deciding to just return if a comma is found. Maybe returning on `)` could also lead to error, but not sure.

WDYT?

**Comment by andybalholm** [comment]
Try using ParseGroup instead of just Parse.

**Comment by krichprollsch** [comment]
`ParseGroup` works as expected thanks :+1: 
But shouldn't `Parse` work with a group also? or do I miss something?

**Comment by andybalholm** [comment]
No, that's the reason ParseGroup exists. The return value from Parse needs to implement all the methods of the Sel interface, and a SelectorGroup doesn't implement Specificity (because the CSS spec doesn't define specificity for selector groups, only for individual selectors).

**Comment by krichprollsch** [comment]
I didn't known about that. Thanks for the explanation.
