### ISSUE TITLE
cannot find package "golang.org/x/net/html" 

### ISSUE THREAD

**Issue by luoxinliang** [andybalholm/cascadia#9]
../../go/src/github.com/andybalholm/cascadia/parser.go:11:2: cannot find package "golang.org/x/net/html" 

Need to update to https://github.com/golang/net ?

**Comment by andybalholm** [comment]
Did you try `go get golang.org/x/net/html`?

**Comment by yogesh-desai** [comment]
Go's get tool is for these kind of tasks.

**Comment by wvxvw-traiana** [comment]
@andybalholm if only it worked, that would be great:
```
can't load package: package golang.org/x/net: no Go files in c:\dev\src\golang.org\x\net
```
Testing allegedly cross-platform tools on all platforms they are alleged for is a mauve-ton now-a-days.

**Comment by stevenkitter** [comment]
timeout . package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by andybalholm** [comment]
Sounds like a network issue to me.

**Comment by rajeshshegokar111** [comment]
i am also getting above issue timeout, network is ok

**Comment by andybalholm** [comment]
Can you access https://golang.org?

**Comment by macleo** [comment]
easy to solve this problem.
before do follow,u ought to make a proxy on your computer.
windows:
//set proxy
set http_proxy=http://localhost:1080
set https_proxy=http://localhost:1080
//cancel proxy
set http_proxy=
//view proxy
set http_proxy
=============================
linux and Mac
export http_proxy=http://localhost:1080
export https_proxy=http://localhost:1080
=============================

then
go get what u want.
